export interface Chart {
  title: string;
  namedQueries: string[];
  data: any[];
  chartSeries: any[];
  pieSeries?: any[];
  stats?: string[],
  type?: string;
  order?: number;
}

export const chartsCfg: Chart[] = [
  {
    title: 'National policy on open access publications',
    namedQueries: ['Question6','Question6.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'mapWithPoints',
    stats: ['Question6','Question6.1'],
    // order: 1
  },
  {
    title: 'Countries with a Specific Policy on Immediate Open Access to Publications',
    namedQueries: ['Question6.3', 'Question6.3.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'mapWithPoints',
    stats: ['Question6.3', 'Question6.3.1'],
    // order: 1
  },
  {
    title: 'Countries with a Specific Policy on Retention of IPR on Publications',
    namedQueries: ['Question6.4', 'Question6.4.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'mapWithPoints',
    stats: ['Question6.4','Question6.4.1'],
    // order: 1
  },
  {
    title: 'Countries with a Specific Policy on Open Licensing of Publications',
    namedQueries: ['Question6.5', 'Question6.5.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'mapWithPoints',
    stats: ['Question6.5', 'Question6.5.1'],
  },
  {
    title: 'Countries with a Financial Strategy on Open Access to Publications',
    namedQueries: ['Question7'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'mapWithPoints',
    stats: ['Question7'],
  },
  {
    title: 'Countries with a National Monitoring on Open Access to Publications',
    namedQueries: ['Question54'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'mapWithPoints',
    stats: ['Question54'],
  },
  {
    title: 'Share of EU Countries with National Investments in Open Access to Publications per 1000 FTE Researchers',
    namedQueries: ['Question56', 'Question1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'rangeColumns',
    stats: ['Question56'],
  },
  {
    title: 'National Policy on Open Access to Publications',
    namedQueries: ['Question6', 'Question6.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'stackedBars',
    stats: ['Question6'],
  },
  {
    title: 'Specific Policy on Immediate Open Access to Publications',
    namedQueries: ['Question6.3', 'Question6.3.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'stackedBars',
    stats: ['Question6.3'],
  },
  {
    title: 'Specific Policy on Retention of IPR on Publications',
    namedQueries: ['Question6.4', 'Question6.4.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'stackedBars',
    stats: ['Question6.4'],
  },
  {
    title: 'Specific Policy on Open Licensing of Publications',
    namedQueries: ['Question6.5', 'Question6.5.1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'stackedBars',
    stats: ['Question6.5'],
  },
  {
    title: 'Financial Strategy on Open Access to Publications',
    namedQueries: ['Question7'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'barChart',
    stats: ['Question7'],
  },
  {
    title: 'National Monitoring on Open Access to Publications',
    namedQueries: ['Question54'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'barChart',
    stats: ['Question54'],
  },
  {
    title: 'Trend in EU Countries with National Investments in Open Access to Publications per 1000 FTE Researchers',
    namedQueries: ['Question56', 'Question1'],
    data: [],
    chartSeries: [],
    pieSeries: [],
    type: 'totalInvestments',
    stats: ['Question56_trend'],
  },
  // {
  //   title: 'National policy on data management',
  //   namedQueries: ['Question10','Question10.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   type: 'mapWithPoints',
  //   stats: ['Question10','Question10.1'],
  //   // order: 2
  // },
  // {
  //   title: 'National policy on FAIR data',
  //   namedQueries: ['Question14','Question14.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question14','Question14.1'],
  // },
  // {
  //   title: 'National policy on open data',
  //   namedQueries: ['Question18','Question18.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question18','Question18.1'],
  // },
  // {
  //   title: 'Financial Strategy on Data Management',
  //   namedQueries: ['Question11'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question11'],
  // },
  // {
  //   title: 'Countries with a Financial Strategy on FAIR Data',
  //   namedQueries: ['Question15'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question15'],
  // },
  // {
  //   title: 'Financial Strategy on Open Data',
  //   namedQueries: ['Question19'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question19'],
  // },
  // {
  //   title: 'National Monitoring on Data Management',
  //   namedQueries: ['Question58'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question58'],
  // },
  // {
  //   title: 'National Monitoring on FAIR Data',
  //   namedQueries: ['Question62'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question62'],
  // },
  // {
  //   title: 'National Monitoring on Open Data',
  //   namedQueries: ['Question66'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question66'],
  // },
  // {
  //   title: 'National Policy on Open Source Software',
  //   namedQueries: ['Question22','Question22.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question22','Question22.1'],
  // },
  // {
  //   title: 'National Monitoring on Open Source Software',
  //   namedQueries: ['Question70'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question70'],
  // },
  // {
  //   title: 'National Policy on Offering Services through EOSC',
  //   namedQueries: ['Question26','Question26.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question26','Question26.1'],
  // },
  // {
  //   title: 'National Monitoring on Offering Services through EOSC',
  //   namedQueries: ['Question74'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question74'],
  // },
  // {
  //   title: 'National Policy on Connecting Repositories to EOSC',
  //   namedQueries: ['Question30','Question30.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question30','Question30.1'],
  // },
  // {
  //   title: 'National Policy on Data Stewardship',
  //   namedQueries: ['Question34','Question34.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question34','Question34.1'],
  // },
  // {
  //   title: 'National Policy on Long-term Data Preservation',
  //   namedQueries: ['Question38','Question38.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question38','Question38.1'],
  // },
  // {
  //   title: 'Financial Strategy on Connecting Repositories to EOSC',
  //   namedQueries: ['Question31'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question31'],
  // },
  // {
  //   title: 'Financial Strategy on Data Stewardship',
  //   namedQueries: ['Question35'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question35'],
  // },
  // {
  //   title: 'Financial Strategy on Long-term Data Preservation',
  //   namedQueries: ['Question39'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question39'],
  // },
  // {
  //   title: 'National Monitoring on Connecting Repositories to EOSC',
  //   namedQueries: ['Question78'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question78'],
  // },
  // {
  //   title: 'National Monitoring on Data Stewardship',
  //   namedQueries: ['Question82'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question82'],
  // },
  // {
  //   title: 'National Monitoring on Long-term Data Preservation',
  //   namedQueries: ['Question86'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question86'],
  // },
  // {
  //   title: 'National Policy on Skills/Training for Open Science',
  //   namedQueries: ['Question42','Question42.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question42','Question42.1'],
  // },
  // {
  //   title: 'Financial Strategy on Skills/Training for Open Science',
  //   namedQueries: ['Question43'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question43'],
  // },
  // {
  //   title: 'National Monitoring on Skills/Training for Open Science',
  //   namedQueries: ['Question90'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question90'],
  // },
  // {
  //   title: 'National Policy on Incentives/Rewards for Open Science',
  //   namedQueries: ['Question46','Question46.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question46','Question46.1'],
  // },
  // {
  //   title: 'Financial Strategy on Incentives/Rewards for Open Science',
  //   namedQueries: ['Question47'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question47'],
  // },
  // {
  //   title: 'National Policy on Citizen Science',
  //   namedQueries: ['Question50','Question50.1'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question50','Question50.1'],
  // },
  // {
  //   title: 'Financial Strategy on Citizen Science',
  //   namedQueries: ['Question51'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question51'],
  // },
  // {
  //   title: 'National Monitoring on Citizen Science',
  //   namedQueries: ['Question98'],
  //   data: [],
  //   chartSeries: [],
  //   pieSeries: [],
  //   stats: ['Question98'],
  // },
]
